version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:24.18.1
    working_directory: ~/project/backend_notifications
    environment:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/notifications
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Generate Prisma Client
          command: npx prisma generate
      - run:
          name: Run ESLint
          command: npm run lint:check

  unit-tests:
    docker:
      - image: cimg/node:24.18.1
    working_directory: ~/project/backend_notifications
    environment:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/notifications
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Generate Prisma Client
          command: npx prisma generate
      - run:
          name: Run unit tests
          command: npm run test:unit

  build:
    docker:
      - image: cimg/node:24.18.1
    working_directory: ~/project/backend_notifications
    environment:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/notifications
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Generate Prisma Client
          command: npx prisma generate
      - run:
          name: Build backend
          command: npm run build

  coverage:
  docker:
    - image: cimg/node:24.18.1

  working_directory: ~/project/backend_notifications

  environment:
    DATABASE_URL: postgresql://postgres:postgres@localhost:5432/notifications

  steps:
    - checkout:
        path: ~/project

    - run:
        name: Install dependencies
        command: npm ci

    - run:
        name: Generate Prisma Client
        command: npx prisma generate

    - run:
        name: Run tests with coverage
        command: npm run test:cov

    - store_artifacts:
        path: coverage
        destination: coverage

workflows:
  backend-ci:
    jobs:
      - lint
      - unit-tests
      - build
      - coverage