// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';
import { Envs } from './src/config/config';


console.log(Envs.DATABASE_URL);

export default defineConfig({
  schema: 'prisma',

  migrations: {
    path: 'prisma/migrations',
  },

  datasource: {
    url: Envs.DATABASE_URL,
  },
});