import type { Queue } from 'bullmq';

import type { SendNotificationJob } from './contracts/send-notification-job';

import {
  NOTIFICATION_JOB_ATTEMPTS,
  NOTIFICATION_JOB_BACKOFF_DELAY_MS,
  NotificationJobName,
} from './notification-queue.constants';

/**
 * BullMQ is replaced because this is a unit test.
 * Redis and the real BullMQ infrastructure are not required here.
 */
jest.mock('@nestjs/bullmq', () => ({
  InjectQueue: () => () => undefined,
}));

import { NotificationQueueProducer } from './notification-queue.producer';

describe('NotificationQueueProducer', () => {
  let producer: NotificationQueueProducer;

  const queueAddMock = jest.fn();

  const queueMock = {
    add: queueAddMock,
  };

  const userId = '65d6e602-ca87-4fc1-aac5-971f36a22aaa';

  const notificationId = '70a7ad1a-8871-4b94-afca-201e8f6f0225';

  beforeEach(() => {
    jest.clearAllMocks();

    producer = new NotificationQueueProducer(
      queueMock as unknown as Queue<SendNotificationJob>,
    );
  });

  it('should enqueue a notification with retry and deduplication options', async () => {
    queueAddMock.mockResolvedValue({
      id: '10',
    });

    const result = await producer.enqueueSend(userId, notificationId);

    expect(queueAddMock).toHaveBeenCalledWith(
      NotificationJobName.SEND,
      {
        userId,
        notificationId,
      },
      {
        attempts: NOTIFICATION_JOB_ATTEMPTS,

        backoff: {
          type: 'exponential',
          delay: NOTIFICATION_JOB_BACKOFF_DELAY_MS,
        },

        removeOnComplete: {
          count: 1_000,
        },

        removeOnFail: {
          count: 5_000,
        },

        deduplication: {
          id: notificationId,
        },
      },
    );

    expect(result).toBe('10');
  });

  it('should return the job id generated by BullMQ', async () => {
    queueAddMock.mockResolvedValue({
      id: '25',
    });

    const result = await producer.enqueueSend(userId, notificationId);

    expect(result).toBe('25');
  });
});
