import { InjectQueue } from '@nestjs/bullmq';
import { Injectable } from '@nestjs/common';

import type { Queue } from 'bullmq';

import type { SendNotificationJob } from './contracts/send-notification-job';

import {
  NOTIFICATION_JOB_ATTEMPTS,
  NOTIFICATION_JOB_BACKOFF_DELAY_MS,
  NOTIFICATION_QUEUE,
  NotificationJobName,
} from './notification-queue.constants';

/**
 * Produces asynchronous notification delivery jobs.
 */
@Injectable()
export class NotificationQueueProducer {
  constructor(
    @InjectQueue(NOTIFICATION_QUEUE)
    private readonly _notificationQueue: Queue<SendNotificationJob>,
  ) {}

  /**
   * Adds a notification delivery job to the queue.
   *
   * Duplicate requests for the same notification are ignored while an
   * existing job for that notification is still being processed.
   *
   * @param userId Authenticated user identifier.
   * @param notificationId Notification identifier.
   * @returns Identifier generated by BullMQ for the queued job.
   */
  async enqueueSend(
    userId: string,
    notificationId: string,
  ): Promise<string | undefined> {
    const job = await this._notificationQueue.add(
      NotificationJobName.SEND,
      {
        userId,
        notificationId,
      },
      {
        attempts: NOTIFICATION_JOB_ATTEMPTS,

        backoff: {
          type: 'exponential',
          delay: NOTIFICATION_JOB_BACKOFF_DELAY_MS,
        },

        removeOnComplete: {
          count: 1_000,
        },

        removeOnFail: {
          count: 5_000,
        },

        deduplication: {
          id: notificationId,
        },
      },
    );

    return job.id;
  }
}
