import { InjectQueue } from '@nestjs/bullmq';
import { Injectable } from '@nestjs/common';

import type { Queue } from 'bullmq';

import type { SendNotificationJob } from './contracts/send-notification-job';
import {
  NOTIFICATION_QUEUE,
  NotificationJobName,
} from './notification-queue.constants';

/**
 * Produces asynchronous notification delivery jobs.
 */
@Injectable()
export class NotificationQueueProducer {
  constructor(
    @InjectQueue(NOTIFICATION_QUEUE)
    private readonly _notificationQueue: Queue<SendNotificationJob>,
  ) {}

  /**
   * Adds a notification delivery job to the queue.
   *
   * @param userId Authenticated user identifier.
   * @param notificationId Notification identifier.
   * @returns Identifier generated by BullMQ for the queued job.
   */
  async enqueueSend(
    userId: string,
    notificationId: string,
  ): Promise<string | undefined> {
    const job = await this._notificationQueue.add(NotificationJobName.SEND, {
      userId,
      notificationId,
    });

    return job.id;
  }
}
